name: "Setup Rust Cross"
description: "Set up Rust toolchain and cross-rs."
author: "DiscreteTom"

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH

    - name: Setup Cross
      shell: bash
      run: |
        if [ "$(uname -s)" = "Linux" ] && [ "$(uname -m)" = "x86_64" ]; then
          # Use prebuilt binary for Linux x86_64
          mkdir -p /tmp/cross
          curl -L https://github.com/cross-rs/cross/releases/download/v0.2.5/cross-x86_64-unknown-linux-musl.tar.gz -o /tmp/cross/cross.tar.gz
          tar -xzf /tmp/cross/cross.tar.gz -C /tmp/cross
          chmod +x /tmp/cross/cross
          mkdir -p "${CARGO_HOME:-$HOME/.cargo}/bin"
          mv /tmp/cross/cross "${CARGO_HOME:-$HOME/.cargo}/bin/"
        else
          # Build from source for other platforms
          cargo install cross
        fi

branding:
  icon: "box"
  color: "green"
